name: Cleanup deployments and build coverage

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

  build:
    needs: cleanup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image locally
      run: |
        docker build -t cpp-coverage:latest .

    - name: Run build and coverage inside Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace cpp-coverage:latest /bin/bash -c "
          mkdir -p build &&
          cd build &&
          cmake -DCOVERAGE=ON .. &&
          cmake --build . &&
          ctest --output-on-failure &&
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage_filtered.info &&
          genhtml --output-directory coverage coverage_filtered.info
        "

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage
    - name: List coverage directory
      run: ls -la build/coverage

    - name: Deploy coverage report to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/coverage

